version: '3'
services:
  # api:
    # build: .
    # volumes:
    #   - '.:/usr/src/app'
    # ports:
    #   - 3000:3000
    # depends_on:
    #   - db
  db:
    container_name: 'mongodb'
    image: 'mongo'
    ports:
      - 27017:27017
    volumes:
      - ./data:/data/db
  mongo-express:
    image: "mongo-express:latest"
    ports:
      - "8081:8081"
    volumes:
      - ./docker-entrypoint.sh:/docker-entrypoint.sh
    environment:
      ME_CONFIG_MONGODB_SERVER: db
    links:
      - db